# Generated by Django 6.0.2 on 2026-04-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='estado',
            field=models.CharField(choices=[('A', 'Activa'), ('P', 'Pendiente'), ('C', 'Cancelada'), ('I', 'Inactiva/Finalizada')], default='P', max_length=1),
        ),
    ]
